# Results statistics

In [10]:
import pandas as pd
import math

### Averages for each family

In [11]:
df = pd.read_csv("/Users/carminacodre/Desktop/results_proteins/res_fam_conf_sa.csv")
del df['Iteration']
del df['TP']
del df['TN']
del df['FP']
del df['FN']
f1 = []
for i in df.index:
    f, prec, rec, spec, auc = df.loc[i]
    f1.append(2.0 * prec * rec / (prec + rec))
df['F1'] = f1
df

    Superfamily      Prec    Recall      Spec       AUC        F1
0         fam_1  0.897380  1.000000  0.977626  0.988813  0.945915
1         fam_2  1.000000  0.999950  1.000000  0.999975  0.999975
2         fam_3  1.000000  0.999933  1.000000  0.999967  0.999967
3         fam_4  0.847649  1.000000  0.977992  0.988996  0.917543
4         fam_5  0.591761  0.999840  0.931024  0.965432  0.743486
5         fam_6  1.000000  0.999840  1.000000  0.999920  0.999920
6         fam_7  0.687051  0.999933  0.944229  0.972081  0.814477
7         fam_8  0.619671  1.000000  0.938624  0.969312  0.765181
8         fam_9  0.705736  1.000000  0.958304  0.979152  0.827486
9         fam_1  0.760384  0.999956  0.938348  0.969152  0.863868
10        fam_2  1.000000  0.999550  1.000000  0.999775  0.999775
11        fam_3  0.843218  1.000000  0.977233  0.988616  0.914941
12        fam_4  1.000000  0.999933  1.000000  0.999967  0.999967
13        fam_5  0.493038  0.999920  0.897184  0.948552  0.660432
14        fam_6  1.000000  0.999680  1.000000  0.999840  0.999840
15        fam_7  0.602144  1.000000  0.919094  0.959547  0.751672
16        fam_8  0.773898  1.000000  0.970784  0.985392  0.872539
17        fam_9  0.869142  1.000000  0.984944  0.992472  0.929990
18        fam_1  0.814863  1.000000  0.955548  0.977774  0.897989
19        fam_2  1.000000  0.999700  1.000000  0.999850  0.999850
20        fam_3  0.997672  0.999800  0.999714  0.999757  0.998735
21        fam_4  0.998469  0.999733  0.999812  0.999773  0.999101
22        fam_5  0.653287  1.000000  0.946928  0.973464  0.790289
23        fam_6  1.000000  0.999840  1.000000  0.999920  0.999920
24        fam_7  0.630501  0.999933  0.928245  0.964089  0.773364
25        fam_8  0.999680  0.999920  0.999968  0.999944  0.999800
26        fam_9  0.835774  0.999920  0.980352  0.990136  0.910508
27        fam_1  0.946052  0.999956  0.988843  0.994400  0.972257
28        fam_2  1.000000  0.999200  1.000000  0.999600  0.999600
29        fam_3  1.000000  0.999867  1.000000  0.999933  0.999933
..          ...       ...       ...       ...       ...       ...
150       fam_7  0.584750  1.000000  0.913045  0.956522  0.737971
151       fam_8  0.636878  1.000000  0.942984  0.971492  0.778162
152       fam_9  0.718664  0.999920  0.960856  0.980388  0.836277
153       fam_1  0.819158  0.999956  0.956809  0.978382  0.900572
154       fam_2  0.998702  1.000000  0.999779  0.999889  0.999350
155       fam_3  1.000000  0.999533  1.000000  0.999767  0.999767
156       fam_4  0.754983  1.000000  0.960261  0.980131  0.860388
157       fam_5  0.494422  0.999760  0.897768  0.948764  0.661637
158       fam_6  1.000000  0.999840  1.000000  0.999920  0.999920
159       fam_7  0.691722  1.000000  0.945429  0.972714  0.817773
160       fam_8  0.976257  1.000000  0.997568  0.998784  0.987986
161       fam_9  0.824974  1.000000  0.978784  0.989392  0.904094
162       fam_1  0.719954  1.000000  0.923896  0.961948  0.837178
163       fam_2  0.991915  0.999950  0.998613  0.999281  0.995917
164       fam_3  0.948037  0.999800  0.993290  0.996545  0.973231
165       fam_4  0.849762  1.000000  0.978351  0.989176  0.918780
166       fam_5  0.422344  0.999840  0.863248  0.931544  0.593842
167       fam_6  1.000000  0.999920  1.000000  0.999960  0.999960
168       fam_7  0.800801  0.999933  0.969543  0.984738  0.889357
169       fam_8  0.600586  1.000000  0.933496  0.966748  0.750458
170       fam_9  0.762660  1.000000  0.968880  0.984440  0.865351
171       fam_1  0.821191  0.999956  0.957400  0.978678  0.901800
172       fam_2  1.000000  0.999650  1.000000  0.999825  0.999825
173       fam_3  0.998402  0.999867  0.999804  0.999835  0.999134
174       fam_4  0.976432  0.999867  0.997045  0.998456  0.988011
175       fam_5  0.697934  1.000000  0.956720  0.978360  0.822098
176       fam_6  1.000000  0.999920  1.000000  0.999960  0.999960
177       fam_7  0.416412  1.000000  0.828392  0.914196  0.587982
178       fam_8  0.995223  1.000000  0.999520  0.999760  0.997606
179       fam_9  0.854224  0.999920  0.982936  0.991428  0.921347

[180 rows x 6 columns]

In [12]:
print("Precision")
avg_fam = df.groupby(['Superfamily'])['Prec'].agg(['mean', 'count', 'std'])
avg_fam
ci = []
for i in avg_fam.index:
    m, c, s = avg_fam.loc[i]
    ci.append(1.96*s/math.sqrt(c))
avg_fam['ci95'] = ci
avg_fam

Precision

                 mean  count       std      ci95
Superfamily
fam_1        0.776085     20  0.116489  0.051054
fam_2        0.990690     20  0.036599  0.016040
fam_3        0.986748     20  0.036575  0.016030
fam_4        0.902521     20  0.096698  0.042380
fam_5        0.604140     20  0.159704  0.069993
fam_6        1.000000     20  0.000000  0.000000
fam_7        0.641853     20  0.095509  0.041858
fam_8        0.808877     20  0.137865  0.060422
fam_9        0.750097     20  0.100578  0.044080

In [13]:
print("Recall")
avg_fam = df.groupby(['Superfamily'])['Recall'].agg(['mean', 'count', 'std'])
avg_fam
ci = []
for i in avg_fam.index:
    m, c, s = avg_fam.loc[i]
    ci.append(1.96*s/math.sqrt(c))
avg_fam['ci95'] = ci
avg_fam

Recall

                 mean  count       std      ci95
Superfamily
fam_1        0.999987     20  0.000021  0.000009
fam_2        0.999690     20  0.000284  0.000124
fam_3        0.999670     20  0.000283  0.000124
fam_4        0.999940     20  0.000081  0.000035
fam_5        0.999924     20  0.000105  0.000046
fam_6        0.999868     20  0.000098  0.000043
fam_7        0.999947     20  0.000083  0.000036
fam_8        0.999956     20  0.000076  0.000033
fam_9        0.999952     20  0.000088  0.000038

In [14]:
print("Spec")
avg_fam = df.groupby(['Superfamily'])['Spec'].agg(['mean', 'count', 'std'])
avg_fam
ci = []
for i in avg_fam.index:
    m, c, s = avg_fam.loc[i]
    ci.append(1.96*s/math.sqrt(c))
avg_fam['ci95'] = ci
avg_fam

Spec

                 mean  count       std      ci95
Superfamily
fam_1        0.936311     20  0.051670  0.022645
fam_2        0.998139     20  0.007454  0.003267
fam_3        0.998171     20  0.005247  0.002300
fam_4        0.985130     20  0.016262  0.007127
fam_5        0.922620     20  0.048002  0.021038
fam_6        1.000000     20  0.000000  0.000000
fam_7        0.926724     20  0.035872  0.015722
fam_8        0.972776     20  0.022435  0.009833
fam_9        0.963281     20  0.027696  0.012138

In [15]:
print("AUC")
avg_fam = df.groupby(['Superfamily'])['AUC'].agg(['mean', 'count', 'std'])
avg_fam
ci = []
for i in avg_fam.index:
    m, c, s = avg_fam.loc[i]
    ci.append(1.96*s/math.sqrt(c))
avg_fam['ci95'] = ci
avg_fam

AUC

                 mean  count       std      ci95
Superfamily
fam_1        0.968149     20  0.025832  0.011322
fam_2        0.998915     20  0.003708  0.001625
fam_3        0.998921     20  0.002578  0.001130
fam_4        0.992535     20  0.008107  0.003553
fam_5        0.961272     20  0.023998  0.010518
fam_6        0.999934     20  0.000049  0.000021
fam_7        0.963335     20  0.017918  0.007853
fam_8        0.986366     20  0.011210  0.004913
fam_9        0.981617     20  0.013841  0.006066

In [17]:
print("F1")
avg_fam = df.groupby(['Superfamily'])['F1'].agg(['mean', 'count', 'std'])
avg_fam
ci = []
for i in avg_fam.index:
    m, c, s = avg_fam.loc[i]
    ci.append(1.96*s/math.sqrt(c))
avg_fam['ci95'] = ci
avg_fam

F1

                 mean  count       std      ci95
Superfamily
fam_1        0.868823     20  0.082102  0.035983
fam_2        0.994821     20  0.019914  0.008728
fam_3        0.992820     20  0.019672  0.008622
fam_4        0.946041     20  0.055819  0.024464
fam_5        0.741408     20  0.124981  0.054775
fam_6        0.999934     20  0.000049  0.000021
fam_7        0.777687     20  0.075482  0.033081
fam_8        0.888151     20  0.085398  0.037427
fam_9        0.853108     20  0.075142  0.032932

In [18]:
avg_fam['mean'].agg(['mean', 'count', 'std'])

mean     0.895866
count    9.000000
std      0.095513
Name: mean, dtype: float64

### Averages Overall

In [8]:
df = pd.read_csv("/Users/carminacodre/Desktop/results_proteins/res_avg_conf_sa.csv")
del df['Iteration']
df

        Prec    Recall      Spec       AUC
0   0.816583  0.999944  0.969755  0.984850
1   0.815758  0.999893  0.965287  0.982590
2   0.881138  0.999872  0.978952  0.989412
3   0.823408  0.999841  0.965497  0.982669
4   0.832098  0.999922  0.969204  0.984563
5   0.869180  0.999867  0.977215  0.988541
6   0.803607  0.999862  0.955726  0.977794
7   0.822051  0.999771  0.968370  0.984071
8   0.790570  0.999915  0.947329  0.973622
9   0.777384  0.999976  0.956883  0.978429
10  0.891150  0.999787  0.983823  0.991805
11  0.863394  0.999812  0.976885  0.988349
12  0.833571  0.999817  0.970683  0.985250
13  0.826112  0.999904  0.967238  0.983571
14  0.855072  0.999875  0.974803  0.987339
15  0.777392  0.999926  0.946363  0.973145
16  0.810878  0.999899  0.967710  0.983805
17  0.840024  0.999899  0.970711  0.985305
18  0.788451  0.999938  0.958813  0.979376
19  0.862202  0.999909  0.969091  0.984500

In [9]:
avg = df.agg(['mean', 'count', 'std']).T
ci = []
for i in avg.index:
    m, c, s = avg.loc[i]
    ci.append(1.96*s/math.sqrt(c))
avg['ci95'] = ci
avg

            mean  count       std      ci95
Prec    0.829001   20.0  0.033366  0.014623
Recall  0.999881   20.0  0.000054  0.000024
Spec    0.967017   20.0  0.009867  0.004325
AUC     0.983449   20.0  0.004920  0.002156